[package]
name = "spandex"
version = "0.0.3"
description = "A modern LaTeX alternative"
authors = ["Thomas Forgione <thomas@forgione.fr>", "Matthieu Le Boucher <matt.leboucher@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
homepage = "https://rust-spandex.github.io"
documentation = "https://rust-spandex.github.io/spandex"
repository = "https://github.com/rust-spandex/spandex"
readme = "README.md"
keywords = ["tex", "latex", "typesetting"]
categories = ["template-engine", "visualization", "text-processing"]

[badges]
travis-ci = { repository = "rust-spandex/spandex", branch = "master" }

[dependencies]
freetype-rs = "0.19.1"
printpdf = "0.2.10"
clap = "2.33.0"
toml = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
hyphenation = { version = "0.7.1", features = ["embed_all"] }
petgraph = "0.4.13"
nom = "4.2.3"
nom_locate = "0.3.1"
colored = "1.8.0"
bincode = "1.1.4"
